import $ from 'mol_wire_lib'

export { $ }

const {
  $mol_after_frame,
  $mol_after_timeout,
  $mol_ambient,
  $mol_compare_deep,
  $mol_fail_hidden,
  $mol_guid,
  $mol_log3_area_lazy,
  $mol_log3_area,
  $mol_log3_come,
  $mol_log3_done,
  $mol_log3_fail,
  $mol_log3_rise,
  $mol_log3_stack,
  $mol_log3_warn,
  $mol_object,
  $mol_state_time,
  $mol_wait_timeout_async,
  $mol_wait_timeout,
  $mol_wire_async,
  $mol_wire_atom,
  $mol_wire_auto,
  $mol_wire_cursor,
  $mol_wire_field,
  $mol_wire_method,
  $mol_wire_plex,
  $mol_wire_solo,
  $mol_wire_sync,
  $mol_wire_task,
} = $

export {
  $mol_after_frame,
  $mol_after_timeout,
  $mol_ambient,
  $mol_compare_deep,
  $mol_fail_hidden,
  $mol_guid,
  $mol_log3_area_lazy,
  $mol_log3_area,
  $mol_log3_come,
  $mol_log3_done,
  $mol_log3_fail,
  $mol_log3_rise,
  $mol_log3_stack,
  $mol_log3_warn,
  $mol_object,
  $mol_state_time,
  $mol_wait_timeout_async,
  $mol_wait_timeout,
  $mol_wire_async,
  $mol_wire_atom,
  $mol_wire_auto,
  $mol_wire_cursor,
  $mol_wire_field,
  $mol_wire_method,
  $mol_wire_plex,
  $mol_wire_solo,
  $mol_wire_sync,
  $mol_wire_task,
} // from 'mol_wire_lib'
